### PR TITLE
Use newer version of Cocopa

### PR DESCRIPTION
**Pull request by stigpo**
Use a version of cocopa that supports more advanced inclusion parameters used in RP Pico SDK.

### CODE REVIEW

**Review by lersi — APPROVED** [review]
seems fine, sadly the original cocopa repo seems to be unmaintained

**Comment by lersi** [comment]
The build fails because Microsoft archived their repository and deleted all releases, some of the build process is relaying on these binaries. So all merge requests are blocked until I resolve this issue.

**Comment by stigpo** [comment]
> The build fails because Microsoft archived their repository and deleted all releases, some of the build process is relaying on these binaries. So all merge requests are blocked until I resolve this issue.

Yes, I noticed. I don't know what the old string_decoder did and the repo seems to have some other issues too, but to get something to compile, I just dropped string_decoder and upgraded nan. This let me build it on Windows and produced a valid cocopa.js in out that I could "hot swap" into the marketplace installed version, so now I have a working extension with support for the inclusions used in Pico.

**Comment by lersi** [comment]
Sorry for the long delay, had busy personal life.
I have fixed the build system and dependencies, please pull the latest changes from main

**Comment by lersi** [comment]
Nice, thank you very much!

**Pull request merged**
